version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.11.1
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.11.1
    ports:
      - 5601:5601

  fluentd:
    image: my-fluentd
    volumes:
      - ./:/fluentd/etc/
    ports:
      - 24224:24224
      - 24224:24224/udp
    environment:
      - FLUENTD_CONF=fluent-efk.conf

  api:
    image: my-app-log
    ports:
      - 8080:8080
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}.{{.ImageName}}"
